export const Configuration = {
    StartSeconds: 60,
    ThreeSixNineSeconds: 10,
    MaxNumberOfPlayers: 4,
    ThreeSixNineQuestions: 15,
    OpenDoorAnswers: 4,
    OpenDoorSeconds: 20,
    PuzzleAnswers: 3,
    PuzzleSeconds: 30,
    GalleryQuestions: 10,
    GallerySeconds: 15,
    CollectiveMemoryAnswers: 5,
    CollectiveMemorySeconds: 10,
    FinalsAnswers: 5,
    FinalsSeconds: 20,
}
